const { setCustomClaims } = require('./setCustomClaims')
const { createHealthcareProfessional } = require('./createHealthcareProfessional')
const { accessRequestAPI } = require('./accessRequestAPI')
const { decryptAccessRequestID } = require('./decryptAccessRequestID')
const { LongTermReportAPI } = require('./LongTermReportAPI')
const { deleteHealthcareProfessionals } = require('./deleteHealthcareProfessionals')
const { deleteDocument, scheduleDeletion } = require('./deleteAccessRequest')
const { sendMessage } = require('./sendMessage')
const { getMessages } = require('./getMessages')
const { setReminder } = require('./setReminder')
const { sendEmailToUser } = require('./sendEmailToUser')
const { generateAuthURL } = require('./generateAuthURL')
const { deleteReminderTask } = require('./deleteReminderTask')
const { sendNotification } = require('./sendNotification')

exports.setCustomClaims = setCustomClaims
exports.createHealthcareProfessional = createHealthcareProfessional
exports.accessRequestAPI = accessRequestAPI
exports.decryptAccessRequestID = decryptAccessRequestID
exports.LongTermReportAPI = LongTermReportAPI
exports.deleteDocument = deleteDocument
exports.scheduleDeletion = scheduleDeletion
exports.deleteHealthcareProfessionals = deleteHealthcareProfessionals
exports.sendMessage = sendMessage
exports.getMessages = getMessages
exports.setReminder = setReminder
exports.sendEmailToUser = sendEmailToUser
exports.generateAuthURL = generateAuthURL
exports.deleteReminderTask = deleteReminderTask
exports.sendNotification = sendNotification
